version: '3'
services:
  service:
    build:
      context: .
      dockerfile: docker/java.docker
#    image: ${DOCKER_IMAGE_NAME}
    depends_on:
      - mq
    env_file:
      - docker-compose.env


  mq:
    build:
      context: .
      dockerfile: docker/rabbitmq.docker
    ports:
      - 15672:15672
      - 5672:5672

  tester:
    build:
      context: .
      dockerfile: docker/python.docker
    depends_on:
      - mq
      - service
    env_file:
      - docker-compose.env
#    stdin_open: true
#    tty: true
    # no logs no ops it opens perma tty to allow connect and interact
